import { validationResult } from "express-validator";
//It collects all validation errors generated by validation rules.

const validateResult = (req, res, next) => {
  const errors = validationResult(req);  //Checks the current request and extracts all validation errors.

  if (!errors.isEmpty()) {
    return res.status(400).json({
      message: "Validation failed",
      errors: errors.array().map((error) => ({
        field: error.path,
        message: error.msg,
      })),
    });
  }
  return next();   //If validation passes, the request moves to the next middleware or controller.
};

export default validateResult;


// Request
//    ↓
// Validation Rules
//    ↓
// validateResult Middleware
//    ↓
// Errors? ── Yes → Return 400 Response
//    ↓ No
// Controller Executes